#*****************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Batch_Testing_SNN.tcl: Tcl script for re-creating project 'Batch_Testing_SNN'
#
# Generated by Vivado on Fri Jun 26 23:28:42 +0800 2026
# IP Build 6300035 on Fri Nov 14 10:48:45 MST 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (Batch_Testing_SNN.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_no_seca.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/imports/batch_testing_SNN/output_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/imports/batch_testing_SNN/hidden_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/rate_encoder.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/output_layer.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/rate_encoder_array.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/hidden_layer.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/hidden_subsystem.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/lif_neuron.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/output_layer_TTFS.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/seca_module.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/snn_top.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/system_controller.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/ttfs_encoder.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/ttfs_encoder_array.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/weight_rom.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/snn_hardware_wrapper.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/constrs_1/new/timing_SNN.xdc"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/output_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/hidden_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/labels_300.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/test_batch_300.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/FYP_SNN/demo_labels_3.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/FYP_SNN/demo_samples_3.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/mnist_index3.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/hidden_subsystem_tb.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_demo_tb.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb_no_SECA.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_output_layer.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_rate_encoder_array.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_no_seca.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/demo_labels_3.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/demo_samples_3.mem"
#    "D:/Vivado/Batch_Testing_SNN/snn_demo_tb_behav.wcfg"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_demo_tb.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/mnist_index3.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_seca_ttfs_demo.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/test_batch_300.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/labels_300.mem"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb.sv"
#    "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/utils_1/imports/synth_1/snn_hardware_wrapper.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_no_seca.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/imports/batch_testing_SNN/output_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/imports/batch_testing_SNN/hidden_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/rate_encoder.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/output_layer.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/rate_encoder_array.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/hidden_layer.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/hidden_subsystem.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/lif_neuron.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/output_layer_TTFS.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/seca_module.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/snn_top.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/system_controller.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/ttfs_encoder.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/ttfs_encoder_array.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/weight_rom.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/snn_hardware_wrapper.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/constrs_1/new/timing_SNN.xdc" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/output_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/hidden_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/labels_300.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/test_batch_300.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/FYP_SNN/demo_labels_3.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/FYP_SNN/demo_samples_3.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/mnist_index3.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/hidden_subsystem_tb.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_demo_tb.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb_no_SECA.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_output_layer.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_rate_encoder_array.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_no_seca.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/demo_labels_3.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/demo_samples_3.mem" \
   "D:/Vivado/Batch_Testing_SNN/snn_demo_tb_behav.wcfg" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_demo_tb.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/mnist_index3.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_seca_ttfs_demo.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/test_batch_300.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/labels_300.mem" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb.sv" \
   "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/utils_1/imports/synth_1/snn_hardware_wrapper.dcp" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "Batch_Testing_SNN"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "Batch_Testing_SNN.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "D:/Vivado/Batch_Testing_SNN"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a200tfbg676-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:ac701:part0:1.4" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "D:/Vivado/${_xil_proj_name_}/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "ac701" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "D:/Vivado/${_xil_proj_name_}/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "250" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_no_seca.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/imports/batch_testing_SNN/output_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/imports/batch_testing_SNN/hidden_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/rate_encoder.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/output_layer.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/rate_encoder_array.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/hidden_layer.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/hidden_subsystem.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/lif_neuron.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/output_layer_TTFS.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/seca_module.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/snn_top.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/system_controller.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/ttfs_encoder.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/ttfs_encoder_array.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/weight_rom.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sources_1/new/snn_hardware_wrapper.sv"\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sources_1 $f]
}

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "new/snn_top_no_seca.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "batch_testing_SNN/output_w.mem"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "batch_testing_SNN/hidden_w.mem"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "new/rate_encoder.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/output_layer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/rate_encoder_array.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/hidden_layer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/hidden_subsystem.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/lif_neuron.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/output_layer_TTFS.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/seca_module.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/snn_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/system_controller.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/ttfs_encoder.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/ttfs_encoder_array.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/weight_rom.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/snn_hardware_wrapper.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "snn_hardware_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/constrs_1/new/timing_SNN.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/timing_SNN.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/output_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/hidden_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/labels_300.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/batch_testing_SNN/test_batch_300.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/FYP_SNN/demo_labels_3.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/imports/FYP_SNN/demo_samples_3.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/mnist_index3.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/hidden_subsystem_tb.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_demo_tb.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb_no_SECA.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_output_layer.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_rate_encoder_array.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_no_seca.sv"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb.sv"\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sim_1 $f]
}

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
set file "batch_testing_SNN/output_w.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "batch_testing_SNN/hidden_w.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "batch_testing_SNN/labels_300.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "batch_testing_SNN/test_batch_300.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "FYP_SNN/demo_labels_3.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "FYP_SNN/demo_samples_3.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "new/mnist_index3.mem"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "new/hidden_subsystem_tb.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/snn_demo_tb.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/snn_top_tb_no_SECA.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/tb_output_layer.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/tb_rate_encoder_array.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/snn_top_no_seca.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "new/snn_top_tb.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "snn_top_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "all" -objects $obj

# Create 'sim_1_3_sample_demo' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1_3_sample_demo] ""]} {
  create_fileset -simset sim_1_3_sample_demo
}

# Set 'sim_1_3_sample_demo' fileset object
set obj [get_filesets sim_1_3_sample_demo]
# Import local files from the original project
set files [list \
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/demo_labels_3.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/demo_samples_3.mem"\
 "D:/Vivado/Batch_Testing_SNN/snn_demo_tb_behav.wcfg"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_demo_tb.sv"\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sim_1_3_sample_demo $f]
}

# Set 'sim_1_3_sample_demo' fileset file properties for remote files
# None

# Set 'sim_1_3_sample_demo' fileset file properties for local files
set file "xsim/demo_labels_3.mem"
set file_obj [get_files -of_objects [get_filesets sim_1_3_sample_demo] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "xsim/hidden_w.mem"
set file_obj [get_files -of_objects [get_filesets sim_1_3_sample_demo] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "xsim/output_w.mem"
set file_obj [get_files -of_objects [get_filesets sim_1_3_sample_demo] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "xsim/demo_samples_3.mem"
set file_obj [get_files -of_objects [get_filesets sim_1_3_sample_demo] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "new/snn_demo_tb.sv"
set file_obj [get_files -of_objects [get_filesets sim_1_3_sample_demo] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1_3_sample_demo' fileset properties
set obj [get_filesets sim_1_3_sample_demo]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "snn_demo_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "xsim.simulate.runtime" -value "all" -objects $obj

# Create 'sim_2_seca_impact_demo' fileset (if not found)
if {[string equal [get_filesets -quiet sim_2_seca_impact_demo] ""]} {
  create_fileset -simset sim_2_seca_impact_demo
}

# Set 'sim_2_seca_impact_demo' fileset object
set obj [get_filesets sim_2_seca_impact_demo]
# Import local files from the original project
set files [list \
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/mnist_index3.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/tb_seca_ttfs_demo.sv"\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sim_2_seca_impact_demo $f]
}

# Set 'sim_2_seca_impact_demo' fileset file properties for remote files
# None

# Set 'sim_2_seca_impact_demo' fileset file properties for local files
set file "xsim/hidden_w.mem"
set file_obj [get_files -of_objects [get_filesets sim_2_seca_impact_demo] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "xsim/output_w.mem"
set file_obj [get_files -of_objects [get_filesets sim_2_seca_impact_demo] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "xsim/mnist_index3.mem"
set file_obj [get_files -of_objects [get_filesets sim_2_seca_impact_demo] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "new/tb_seca_ttfs_demo.sv"
set file_obj [get_files -of_objects [get_filesets sim_2_seca_impact_demo] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_2_seca_impact_demo' fileset properties
set obj [get_filesets sim_2_seca_impact_demo]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "tb_seca_ttfs_demo" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "all" -objects $obj

# Create 'sim_3_snn_batch' fileset (if not found)
if {[string equal [get_filesets -quiet sim_3_snn_batch] ""]} {
  create_fileset -simset sim_3_snn_batch
}

# Set 'sim_3_snn_batch' fileset object
set obj [get_filesets sim_3_snn_batch]
# Import local files from the original project
set files [list \
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/hidden_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/output_w.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/test_batch_300.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.sim/sim_1/behav/xsim/labels_300.mem"\
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/sim_1/new/snn_top_tb.sv"\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sim_3_snn_batch $f]
}

# Set 'sim_3_snn_batch' fileset file properties for remote files
# None

# Set 'sim_3_snn_batch' fileset file properties for local files
set file "xsim/hidden_w.mem"
set file_obj [get_files -of_objects [get_filesets sim_3_snn_batch] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "xsim/output_w.mem"
set file_obj [get_files -of_objects [get_filesets sim_3_snn_batch] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "xsim/test_batch_300.mem"
set file_obj [get_files -of_objects [get_filesets sim_3_snn_batch] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "xsim/labels_300.mem"
set file_obj [get_files -of_objects [get_filesets sim_3_snn_batch] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj

set file "new/snn_top_tb.sv"
set file_obj [get_files -of_objects [get_filesets sim_3_snn_batch] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_3_snn_batch' fileset properties
set obj [get_filesets sim_3_snn_batch]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "snn_top_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "xsim.simulate.runtime" -value "all" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 "D:/Vivado/Batch_Testing_SNN/Batch_Testing_SNN.srcs/utils_1/imports/synth_1/snn_hardware_wrapper.dcp"\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset utils_1 $f]
}

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/snn_hardware_wrapper.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a200tfbg676-2 -flow {Vivado Synthesis 2025} -strategy "Flow_RuntimeOptimized" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Flow_RuntimeOptimized" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2025" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "incremental_checkpoint" -value "D:/Vivado/${_xil_proj_name_}/${_xil_proj_name_}.srcs/utils_1/imports/synth_1/snn_hardware_wrapper.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Flow_RuntimeOptimized" -objects $obj
set_property -name "steps.synth_design.args.flatten_hierarchy" -value "none" -objects $obj
set_property -name "steps.synth_design.args.directive" -value "RuntimeOptimized" -objects $obj
set_property -name "steps.synth_design.args.fsm_extraction" -value "off" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a200tfbg676-2 -flow {Vivado Implementation 2025} -strategy "Flow_RuntimeOptimized" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Flow_RuntimeOptimized" [get_runs impl_1]
  set_property flow "Vivado Implementation 2025" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.routable_nets" -value "1" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Flow_RuntimeOptimized" -objects $obj
set_property -name "steps.opt_design.args.directive" -value "RuntimeOptimized" -objects $obj
set_property -name "steps.place_design.args.directive" -value "RuntimeOptimized" -objects $obj
set_property -name "steps.phys_opt_design.is_enabled" -value "0" -objects $obj
set_property -name "steps.route_design.args.directive" -value "RuntimeOptimized" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
